export default Object.freeze({
  LOGIN_VIEW: "LoginScreen",
  MAIN_VIEW: "MainScreen",
  PETS_NAVIGATOR: "PetsNavigator",
  PETS_VIEW: "PetsScreen",
  PET_DETAIL_VIEW: "PetDetail",
  PET_FORM_VIEW: "PetForm",
  DIARY_VIEW: "DiaryScreen",
  DIARY_DETAIL_VIEW: "DiaryDetail",
  DIARY_FORM_VIEW: "DiaryForm",
  CALENDAR_VIEW: "CalendarScreen",
  CALENDAR_FORM_VIEW: "CalendarForm",
  CALENDAR_NAVIGATOR: "CalendarNavigator",
  CALENDAR_DETAIL_VIEW: "CalendarDetail",
  REMINDERS_VIEW: "RemindersScreen",
  PROFILE_VIEW: "ProfileScreen",
  USER_FORM_VIEW: "UserForm",
  HOST: "https://pet-care-tp2bec.herokuapp.com",
  PET_ENDPOINT: "/api/pets",
  REMINDER_ENDPOINT: "/api/reminders",
  DIARY_ENDPOINT: "/api/diaryEntries",
  CALENDAR_ENDPOINT: "/api/calendarEntries",
  USER_ENDPOINT: "/api/users",
  DELETE_CONFIRM: (itemName) => `Delete ${itemName}?`,
  DELETE_CONFIRM_CALENDAR: 'Delete this Calendar Entry?',
  ACTION_CANNOT_BE_REVERSED: "This action cannot be reversed",
  LOGOUT_QUESTION: "Are you sure you want to log out?",
  GENERIC_PETS:
    "https://media.istockphoto.com/photos/group-of-pets-posing-around-a-border-collie-dog-cat-ferret-rabbit-picture-id1296353202?k=20&m=1296353202&s=612x612&w=0&h=-J5RllK3gwzLCkYbLUUPHmGuMxpneC7cfkAKFpfNfuk=",
  GENERIC_PROFILE:
    "https://t4.ftcdn.net/jpg/00/64/67/63/360_F_64676383_LdbmhiNM6Ypzb3FM4PPuFP9rHe7ri8Ju.jpg",
  GENERIC_CALENDAR_ENTRY:
  "https://bloximages.newyork1.vip.townnews.com/nny360.com/content/tncms/assets/v3/editorial/7/8c/78c06da8-4a9c-519d-ab3d-c90cf25b09f6/5f6511dcf0d42.image.jpg?resize=400%2C267",
  DOG: "Dog",
  CAT: "Cat",
  HAMSTER: "Hamster",
  TORTOISE: "Tortoise",
  HORSE: "Horse",
  FISH: "Fish",
  RABBIT: "Rabbit",
});
