export default Object.freeze({
  LOGIN_VIEW: "LoginScreen",
  MAIN_VIEW: "MainScreen",
  PETS_NAVIGATOR: "PetsNavigator",
  PETS_VIEW: "PetsScreen",
  PET_DETAIL_VIEW: "PetDetail",
  PET_FORM_VIEW: "PetForm",
  DIARY_VIEW: "DiaryScreen",
  CALENDAR_VIEW: "CalendarScreen",
  REMINDERS_VIEW: "RemindersScreen",
  HOST: "https://pet-care-tp2bec.herokuapp.com",
  PET_ENDPOINT: "/api/pets",
  REMINDER_ENDPOINT: "/api/reminders",
  DIARY_ENDPOINT: "/api/diaryEntries",
  CALENDAR_ENDPOINT: "/api/calendarEntries",
  USER_ENDPOINT: "/api/users",
});
