export default Object.freeze({
  LOGIN_VIEW: "LoginScreen",
  MAIN_VIEW: "MainScreen",
  PETS_NAVIGATOR: "PetsNavigator",
  PETS_VIEW: "PetsScreen",
  PET_DETAIL_VIEW: "PetDetail",
  PET_FORM_VIEW: "PetForm",
  DIARY_VIEW: "DiaryScreen",
  CALENDAR_VIEW: "CalendarScreen",
  REMINDERS_VIEW: "RemindersScreen",
  PROFILE_VIEW: "ProfileScreen",
  USER_FORM_VIEW: "UserForm",
  HOST: "https://pet-care-tp2bec.herokuapp.com",
  PET_ENDPOINT: "/api/pets",
  REMINDER_ENDPOINT: "/api/reminders",
  DIARY_ENDPOINT: "/api/diaryEntries",
  CALENDAR_ENDPOINT: "/api/calendarEntries",
  USER_ENDPOINT: "/api/users",
  DELETE_CONFIRM: (itemName) => `Delete ${itemName}?`,
  ACTION_CANNOT_BE_REVERSED: "This action cannot be reversed",
  LOGOUT_QUESTION: "Are you sure you want to log out?",
});
