export default Object.freeze({
  PET_SCREEN: "paw",
  DIARY_SCREEN: "notebook",
  CALENDAR_SCREEN: "calendar",
  REMINDERS_SCREEN: "alarm",
  DOG_THUMBNAIL: "dog",
  CAT_THUMBNAIL: "cat",
  HAMSTER_THUMBNAIL: "rodent",
  TORTOISE_THUMBNAIL: "tortoise",
  HORSE_THUMBNAIL: "horseshoe",
  FISH_THUMBNAIL: "fish",
  RABBIT_THUMBNAIL: "rabbit",
  DELETE_BUTTON: "delete-circle",
  EDIT_BUTTON: "file-edit",
  PROFILE_EDIT: "account-edit",
});
